#! /bin/bash

sxhkd -c ~/.config/bspwm/themes/bspwm_city/sxhkd/sxhkdrc &
numlockx &
dunst &
nitrogen --restore &
picom --config ~/.config/bspwm/themes/bspwm_city/picom/picom.conf &
xsetroot -cursor_name left_ptr &
#feh --bg-scale ~/.config/bspwm/themes/bspwm_city/wallpaper/erik-witsoe-pvoQJym18Jg-unsplash_gruvbox.jpg
~/.config/bspwm/themes/bspwm_city/scripts/launch_polybar.sh &
conky -c ~/.config/bspwm/themes/bspwm_city/conky/conky.conf

firefox &
telegram-desktop -startintray &
youtube &
Twitch &
discord &
#whatsapp-for-linux &
#viber &
steam &
dropbox &

#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+750+90
bspc rule -a TelegramDesktop state=floating follow=off rectangle=445x1150+1460+43 split_ratio=0.3
bspc rule -a firefox state=floating follow=off rectangle=1440x1150+10+10 desktop='^1' split_ratio=0.7
#bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a dmenu rectangle=900x22+610+90
bspc rule -a Viewnior rectangle=1350x900+285+90 state=floating
#bspc rule -a Inkscape desktop='^3'
#bspc rule -a Blender desktop='^2'
bspc rule -a discord  state=tiled desktop='^6'
#bspc rule -a whatsapp-for-linux state=tiled desktop='^6'
bspc rule -a Youtube state=tiled desktop='^2'
bspc rule -a Twitch state=tiled desktop='^3'
#bspc rule -a Viber state=tiled desktop='^6'
bspc rule -a steam state=floating desktop ='^7'

bspc monitor -d 󰖟 󰗃        󰙯 󰊗 

bspc config border_width         1
bspc config window_gap           5

bspc config normal_border_color "#928374"
bspc config active_border_color "#928374"
#bspc config focused_border_color "#f9f8fe"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#282828"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	 true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
