[colors.bright]
black = "#7c6f64"
blue = "#83a598"
cyan = "#8ec87c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#fbf1c7"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 10.0

[font.bold]
style = "Bold"

[font.normal]
style = "Regular"

[scrolling]
history = 100

[window]
opacity = 0.8

[window.padding]
x = 15
y = 15
